# Generated by Django 4.2.3 on 2024-10-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectCode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ProjectTitle', models.CharField(max_length=200)),
                ('ProjectDescription', models.TextField()),
                ('ProposalLink', models.CharField(max_length=200)),
                ('Round', models.CharField(max_length=200)),
                ('Pool', models.CharField(max_length=200)),
                ('ContractStatus', models.CharField(max_length=200)),
                ('ContractLink', models.CharField(max_length=200)),
                ('TotalAmount', models.FloatField()),
                ('TotalDisbursed', models.FloatField()),
                ('TotalNumberOfMilestones', models.IntegerField()),
                ('NumberOfDoneMilestones', models.IntegerField()),
                ('PercentageDone', models.FloatField()),
                ('ProjectStatus', models.TextField()),
                ('DateOfLastUpdate', models.TextField()),
                ('HasService', models.BooleanField()),
                ('StartDate', models.TextField()),
                ('EndDate', models.TextField()),
                ('Remark', models.TextField()),
            ],
            options={
                'db_table': 'Projects',
                'managed': False,
            },
        ),
    ]
